### ISSUE TITLE
Touch controller meshes missing

### ISSUE THREAD

**Issue by DionHo** [BastiaanOlij/godot-oculus-asset#3]
Hi Bastian,
you have mentioned that the touch controller meshes are under the oculus licence, but they are currently missing in the repo anyway :). Can you please add the meshes or refer to a link, where I can download them?

Kind regards

**Comment by BastiaanOlij** [comment]
well that makes sense;) .obj files are set to ignored because normally they are compiled source files :)

**Comment by BastiaanOlij** [comment]
Ok, should be there now *fingers crossed*

**Comment by DionHo** [comment]
Works now after I downloaded the meshes additionally. After the AssetLib-Version is updated, everything should be working fine ;) Thanks a lot for your work!
